//
// Created by STEVEN on 10/06/2026.
//

#ifndef HOMEWORK_PROTOTYPE_CANDIDATO_H
#define HOMEWORK_PROTOTYPE_CANDIDATO_H

enum class Candidate {
    KEIKO_FUJIMORI,
    RAFAEL_LOPEZ,
    CESAR_ACUNA,
    VLADIMIR_CERRON,
    ROBERTO_PALOMINO,
};

#endif //HOMEWORK_PROTOTYPE_CANDIDATO_H